name: Hello World with Docker

on: 
 workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . -t 06karthik/hello:latest

    - name: Push the Docker image
      run: docker push 06karthik/hello:latest

    - name: Run Docker container
      run: docker run 06karthik/hello:latest
